### ISSUE TITLE
Documentation for running tests locally is missing

### ISSUE THREAD

**Issue by eventualbuddha** [square/connect-nodejs-sdk#3]
I checked out the project, ran:

```
$ npm install
$ npm test
```

I get this error:

```
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v9.2.1
npm info lifecycle square-connect@2.5.2~pretest: square-connect@2.5.2
npm info lifecycle square-connect@2.5.2~test: square-connect@2.5.2

> square-connect@2.5.2 test /Users/donovan/src/connect-javascript-sdk
> mocha --recursive

fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/Users/donovan/src/connect-javascript-sdk/travis-ci/accounts.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.<anonymous> (/Users/donovan/src/connect-javascript-sdk/test/support/accounts.js:4:32)
    at Module._compile (module.js:641:30)
    at loader (/Users/donovan/src/connect-javascript-sdk/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/donovan/src/connect-javascript-sdk/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/donovan/src/connect-javascript-sdk/test/support/setup.js:1:18)
    at Module._compile (module.js:641:30)
    at loader (/Users/donovan/src/connect-javascript-sdk/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/donovan/src/connect-javascript-sdk/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/donovan/src/connect-javascript-sdk/test/api/ApplePayApi.spec.js:22:5)
    at Module._compile (module.js:641:30)
    at loader (/Users/donovan/src/connect-javascript-sdk/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/donovan/src/connect-javascript-sdk/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /Users/donovan/src/connect-javascript-sdk/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/donovan/src/connect-javascript-sdk/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/donovan/src/connect-javascript-sdk/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/donovan/src/connect-javascript-sdk/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
npm info lifecycle square-connect@2.5.2~test: Failed to exec test script
npm ERR! Test failed.  See above for more details.
```

**Comment by jessdelacruzsantos** [comment]
Thanks for the updating, we're working on this ticket now.

**Comment by okenshields** [comment]
This Square Connect Node SDK will be deprecated in Q4 2020 - please refer to [the deprecation notice in README](https://github.com/square/connect-nodejs-sdk/blob/master/README.md) for more details.
We will improve documentation on running tests in a new SDK which will be available in Q4 2020.
