### ISSUE TITLE
getting code 400

### ISSUE THREAD

**Issue by rush86999** [square/connect-nodejs-sdk#71]
i keep getting string expected error for source_id but when i console.log it, it is a string. I m stumped. Could there be another reason for this error?

the nonce is generated by square react payments form which is in beta but the value is a string.

here's the code

```

const uuid = require('uuid/v4');

const SquareConnect = require('square-connect');

const defaultClient = SquareConnect.ApiClient.instance;

const saveCharge = require('./saveCharge');

module.exports = async (data) => {
  try {
    const {
      tokenId,
      sourceId,
      verifyToken,
    } = data;
    const { oauth2 } = defaultClient.authentications;
    oauth2.accessToken = tokenId;

    const api = new SquareConnect.PaymentsApi();
    console.log({
      source_id: sourceId,
      idempotency_key: uuid(),
      amount_money: {
        amount: 500,
        currency: 'USD',
      },
      app_fee_money: {
        amount: 200,
        currency: 'USD',
      },
      verification_token: verifyToken,
    }, ' this  is paymentobject');
    const body = new SquareConnect.CreatePaymentRequest({
      source_id: sourceId,
      idempotency_key: uuid(),
      amount_money: {
        amount: 500,
        currency: 'USD',
      },
      app_fee_money: {
        amount: 200,
        currency: 'USD',
      },
      verification_token: verifyToken,
    });
    const payment = await api.createPayment(body);

    console.log(payment, 'createPayment called.');

    const savedTransaction = await saveCharge(payment, data);

    return savedTransaction;
  } catch (e) {
    console.error(e);
    return e;
  }
};
```

**Comment by rush86999** [comment]
here's the error
```
'{"errors": [{"code": "EXPECTED_STRING","detail": "Expected a string value (line 1, character 14)","field": "source_id","category": "INVALID_REQUEST_ERROR"}]}\n'
```

**Comment by rush86999** [comment]
here's the callback for a nonce response from square react payments form

```
cardNonceResponseReceived = async (errors, nonce, cardData, buyerVerificationToken) => {
    if (errors) {
      const { creditCardFailureMessage } = this.props;
      console.log(errors, ' this is in cardNonceResponseReceived');
      if (creditCardFailureMessage) creditCardFailureMessage(errors.map(error => error.message));
    }
    try {
      // User clicked submit
      //  const { stripe } = this.props;
      // providerId will come from { match.params.id } = this.props;
      // need to include authorization header as well
      // need email, token and patientId
      //  providerName for possible future refunds

      const {
        merchantId,
        patientId,
        jwtToken,
        providerName,
        accessToken,
      } = this.props;
      // also need the price the customer is paying for
      //  providerId is from url { match.params.id } = this.props;
   
      const url = ENT_SQUARE_SERVER_CHARGE_URL;
      //  const { amount, label } = selectedService;
      const { providerId } = this.props;
      //  const { accessToken, verifyToken } = this.state;
      //  amount in $ convert to cents by * 100
      console.log(nonce, cardData, buyerVerificationToken, ' this is nonce, cardData, buyerVerificationToken');
      const data = JSON.stringify({
        //  charge: true,
        //  email: email,
        tokenId: accessToken,
        sourceId: nonce,
        verifyToken: buyerVerificationToken,
        patientId,
        providerId,
        providerName,
        //  amount,
        //  description: `$25 per visit charge on ${moment().format('LLL')} for ${name}`,
        merchantId,
        //  name,
      });

      // create a subscription
      const config = {
        headers: {
          Authorization: jwtToken,
          'Content-Type': 'application/json',
        },
      };
      const result = await axios.post(url, data, config);
      console.log(result, ' this is submit of token to back-end server.');
      const {
        data: {
          input: {
            response: {
              status,
            },
          },
        },
      } = result;
      if (status !== 200) {
        const { creditCardFailureMessage } = this.props;
        if (creditCardFailureMessage) return creditCardFailureMessage('error');
      }
      const { confirmPaid, creditCardSuccessMessage } = this.props;
      if (confirmPaid) confirmPaid();
      if (creditCardSuccessMessage) creditCardSuccessMessage();
    } catch (e) {
      console.error(e, ' something went wrong in submit action of PatientCheckoutFormSquare');
      const { creditCardFailureMessage } = this.props;
      if (creditCardFailureMessage) creditCardFailureMessage(e);
    }
  }
```

**Comment by rush86999** [comment]
```
import React, { Component } from 'react';
/*
import {
  CardElement, injectStripe,
} from 'react-stripe-elements'; */
import SquarePaymentForm, {
  CreditCardNumberInput,
  CreditCardExpirationDateInput,
  CreditCardPostalCodeInput,
  CreditCardCVVInput,
  CreditCardSubmitButton,
} from 'react-square-payment-form';
import 'react-square-payment-form/lib/default.css';

import { withRouter } from 'react-router-dom';
import axios from 'axios';

//  const moment = require('moment-timezone');

const ENT_SQUARE_SERVER_CHARGE_URL = process.env.REACT_APP_SQUARE_CHARGE;
// const PROVIDER_ID = '33c99248-3a94-47a6-9677-8cf0bc751e6c';

const APPLICATION_ID = 'sq0idp---72YFiD8aOH5cn3F1XVHw';
const LOCATION_ID = '3GYC2DYQNGR03';

class PatientCheckoutForm extends Component {
  cardNonceResponseReceived = async (errors, nonce, cardData, buyerVerificationToken) => {
    if (errors) {
      const { creditCardFailureMessage } = this.props;
      console.log(errors, ' this is in cardNonceResponseReceived');
      if (creditCardFailureMessage) creditCardFailureMessage(errors.map(error => error.message));
    }
    try {
      // User clicked submit
      //  const { stripe } = this.props;
      // providerId will come from { match.params.id } = this.props;
      // need to include authorization header as well
      // need email, token and patientId
      //  providerName for possible future refunds

      const {
        merchantId,
        patientId,
        jwtToken,
        providerName,
        accessToken,
      } = this.props;
      // also need the price the customer is paying for
      //  providerId is from url { match.params.id } = this.props;
      //  const { token } = await stripe.createToken({ name });
      const url = ENT_SQUARE_SERVER_CHARGE_URL;
      //  const { amount, label } = selectedService;
      const { providerId } = this.props;
      //  const { accessToken, verifyToken } = this.state;
      //  amount in $ convert to cents by * 100
      console.log(nonce, cardData, buyerVerificationToken, ' this is nonce, cardData, buyerVerificationToken');
      const data = JSON.stringify({
        //  charge: true,
        //  email: email,
        tokenId: accessToken,
        sourceId: nonce,
        verifyToken: buyerVerificationToken,
        patientId,
        providerId,
        providerName,
        //  amount,
        //  description: `$25 per visit charge on ${moment().format('LLL')} for ${name}`,
        merchantId,
        //  name,
      });

      // create a subscription
      const config = {
        headers: {
          Authorization: jwtToken,
          'Content-Type': 'application/json',
        },
      };
      const result = await axios.post(url, data, config);
      console.log(result, ' this is submit of token to back-end server.');
      const {
        data: {
          input: {
            response: {
              status,
            },
          },
        },
      } = result;
      if (status !== 200) {
        const { creditCardFailureMessage } = this.props;
        if (creditCardFailureMessage) return creditCardFailureMessage('error');
      }
      const { confirmPaid, creditCardSuccessMessage } = this.props;
      if (confirmPaid) confirmPaid();
      if (creditCardSuccessMessage) creditCardSuccessMessage();
    } catch (e) {
      console.error(e, ' something went wrong in submit action of PatientCheckoutFormSquare');
      const { creditCardFailureMessage } = this.props;
      if (creditCardFailureMessage) creditCardFailureMessage(e);
    }
  }

  createVerificationDetails = () => {
    const {
      lastName,
      firstName,
      email,
      city,
      address1,
      address2,
      postalCode,
      phone,
    } = this.props;
    return {
      amount: '25.00',
      currencyCode: 'USD',
      intent: 'CHARGE',
      billingContact: {
        familyName: lastName,
        givenName: firstName,
        email,
        country: 'US',
        city,
        addressLines: [address1, address2],
        postalCode,
        phone,
      },
    };
  }

  render() {
    return (
      <div className="dt w-100-ns checkout mw3 mw5-ns center blue">
        <div className="dtc v-mid pa2">
          <p>
            Would you like to complete the purchase?
          </p>
          <SquarePaymentForm
            className="h3-ns h2 ma3 ma2-ns"
            applicationId={APPLICATION_ID}
            locationId={LOCATION_ID}
            cardNonceResponseReceived={this.cardNonceResponseReceived}
            createVerificationDetails={this.createVerificationDetails}
            {...this.props}
          >
            <fieldset className="sq-fieldset">
              <CreditCardNumberInput />
              <div className="sq-form-third">
                <CreditCardExpirationDateInput />
              </div>

              <div className="sq-form-third">
                <CreditCardPostalCodeInput />
              </div>

              <div className="sq-form-third">
                <CreditCardCVVInput />
              </div>
            </fieldset>
            <CreditCardSubmitButton>
                Pay
            </CreditCardSubmitButton>
          </SquarePaymentForm>
        </div>
      </div>
    );
  }
}

//  const PatientCheckoutFormInjectSquare = injectStripe(PatientCheckoutForm);

const PatientCheckoutFormWithRouter = withRouter(PatientCheckoutForm);

export default PatientCheckoutFormWithRouter;

```

**Comment by rush86999** [comment]
```
2019-10-23T21:57:17.209Z 58d0ad18-4cee-4541-8701-118f853f72bd ERROR { Error: Bad Request
at Request.callback (/var/task/node_modules/superagent/lib/node/index.js:706:15)
at IncomingMessage.parser (/var/task/node_modules/superagent/lib/node/index.js:916:18)
at IncomingMessage.emit (events.js:203:15)
at IncomingMessage.EventEmitter.emit (domain.js:448:20)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
status: 400,
response:
Response {
domain: null,
_events: [Object: null prototype] {},
_eventsCount: 0,
_maxListeners: undefined,
res:
IncomingMessage {
_readableState: [ReadableState],
readable: false,
domain: null,
_events: [Object],
_eventsCount: 4,
_maxListeners: undefined,
socket: [TLSSocket],
connection: [TLSSocket],
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
headers: [Object],
rawHeaders: [Array],
trailers: {},
rawTrailers: [],
aborted: false,
upgrade: false,
url: '',
method: null,
statusCode: 400,
statusMessage: 'Bad Request',
client: [TLSSocket],
_consuming: false,
_dumped: false,
req: [ClientRequest],
text:
'{"errors": [{"code": "EXPECTED_STRING","detail": "Expected a string value (line 1, character 14)","field": "source_id","category": "INVALID_REQUEST_ERROR"}]}\n' },
request:
Request {
domain: null,
_events: [Object: null prototype] {},
_eventsCount: 0,
_maxListeners: undefined,
_agent: false,
_formData: null,
method: 'POST',
url: 'https://connect.squareup.com/v2/payments',
_header: [Object],
header: [Object],
writable: true,
_redirects: 0,
_maxRedirects: 5,
cookies: '',
qs: {},
_query: [],
qsRaw: [],
_redirectList: [],
_streamRequest: false,
_timeout: 60000,
_responseTimeout: 0,
_data: [Object],
req: [ClientRequest],
protocol: 'https:',
host: 'connect.squareup.com',
_endCalled: true,
_callback: [Function],
res: [IncomingMessage],
response: [Circular],
called: true },
req:
ClientRequest {
domain: null,
_events: [Object],
_eventsCount: 3,
_maxListeners: undefined,
output: [],
outputEncodings: [],
outputCallbacks: [],
outputSize: 0,
writable: true,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: false,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: 279,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket: [TLSSocket],
connection: [TLSSocket],
_header:
'POST /v2/payments HTTP/1.1\r\nHost: connect.squareup.com\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Square-Connect-Javascript/2.20190925.0\r\nAuthorization: Bearer EAAAEByjBkQbaCvbJYRxUjqw6uuhoPkJDYSDfyX0VNYb0umiubl6WFVIZT1BywGa\r\nSquare-Version: 2019-09-25\r\nContent-Type: application/json\r\nAccept: application/json\r\nContent-Length: 279\r\nConnection: close\r\n\r\n',
_onPendingData: [Function: noopPendingOutput],
agent: [Agent],
socketPath: undefined,
timeout: undefined,
method: 'POST',
path: '/v2/payments',
_ended: true,
res: [IncomingMessage],
aborted: undefined,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
[Symbol(isCorked)]: false,
[Symbol(outHeadersKey)]: [Object] },
text:
'{"errors": [{"code": "EXPECTED_STRING","detail": "Expected a string value (line 1, character 14)","field": "source_id","category": "INVALID_REQUEST_ERROR"}]}\n',
body: {},
files: undefined,
buffered: true,
headers:
{ date: 'Wed, 23 Oct 2019 21:57:17 GMT',
'frame-options': 'DENY',
'x-frame-options': 'DENY',
'x-content-type-options': 'nosniff',
'x-xss-protection': '1; mode=block',
'keep-alive': 'timeout=60',
'strict-transport-security': 'max-age=631152000',
'content-length': '158',
connection: 'close' },
header:
{ date: 'Wed, 23 Oct 2019 21:57:17 GMT',
'frame-options': 'DENY',
'x-frame-options': 'DENY',
'x-content-type-options': 'nosniff',
'x-xss-protection': '1; mode=block',
'keep-alive': 'timeout=60',
'strict-transport-security': 'max-age=631152000',
'content-length': '158',
connection: 'close' },
statusCode: 400,
status: 400,
statusType: 4,
info: false,
ok: false,
redirect: false,
clientError: true,
serverError: false,
error:
{ Error: cannot POST /v2/payments (400)
at Response.toError (/var/task/node_modules/superagent/lib/node/response.js:94:15)
at ResponseBase._setStatusProperties (/var/task/node_modules/superagent/lib/response-base.js:123:16)
at new Response (/var/task/node_modules/superagent/lib/node/response.js:41:8)
at Request._emitResponse (/var/task/node_modules/superagent/lib/node/index.js:752:20)
at IncomingMessage.parser (/var/task/node_modules/superagent/lib/node/index.js:916:38)
at IncomingMessage.emit (events.js:203:15)
at IncomingMessage.EventEmitter.emit (domain.js:448:20)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
status: 400,
text:
'{"errors": [{"code": "EXPECTED_STRING","detail": "Expected a string value (line 1, character 14)","field": "source_id","category": "INVALID_REQUEST_ERROR"}]}\n',
method: 'POST',
path: '/v2/payments' },
created: false,
accepted: false,
noContent: false,
badRequest: true,
unauthorized: false,
notAcceptable: false,
forbidden: false,
notFound: false,
unprocessableEntity: false,
type: '',
links: {},
setEncoding: [Function: bound ],
redirects: [] } }
```

**Comment by rush86999** [comment]
```
import React, { Component } from 'react';
/*
import {
  CardElement, injectStripe,
} from 'react-stripe-elements'; */
import SquarePaymentForm, {
  CreditCardNumberInput,
  CreditCardExpirationDateInput,
  CreditCardPostalCodeInput,
  CreditCardCVVInput,
  CreditCardSubmitButton,
} from 'react-square-payment-form';
import 'react-square-payment-form/lib/default.css';

import { withRouter } from 'react-router-dom';
import axios from 'axios';

//  const moment = require('moment-timezone');

const ENT_SQUARE_SERVER_CHARGE_URL = process.env.REACT_APP_SQUARE_CHARGE;
// const PROVIDER_ID = '33c99248-3a94-47a6-9677-8cf0bc751e6c';

const APPLICATION_ID = 'sq0idp---72YFiD8aOH5cn3F1XVHw';
const LOCATION_ID = '3GYC2DYQNGR03';

class PatientCheckoutForm extends Component {
  cardNonceResponseReceived = async (errors, nonce, cardData, buyerVerificationToken) => {
    if (errors) {
      const { creditCardFailureMessage } = this.props;
      console.log(errors, ' this is in cardNonceResponseReceived');
      if (creditCardFailureMessage) creditCardFailureMessage(errors.map(error => error.message));
    }
    try {
      // User clicked submit
      //  const { stripe } = this.props;
      // providerId will come from { match.params.id } = this.props;
      // need to include authorization header as well
      // need email, token and patientId
      //  providerName for possible future refunds

      const {
        merchantId,
        patientId,
        jwtToken,
        providerName,
        accessToken,
      } = this.props;
      // also need the price the customer is paying for
      //  providerId is from url { match.params.id } = this.props;
      //  const { token } = await stripe.createToken({ name });
      const url = ENT_SQUARE_SERVER_CHARGE_URL;
      //  const { amount, label } = selectedService;
      const { providerId } = this.props;
      //  const { accessToken, verifyToken } = this.state;
      //  amount in $ convert to cents by * 100
      console.log(nonce, cardData, buyerVerificationToken, ' this is nonce, cardData, buyerVerificationToken');
      const data = JSON.stringify({
        //  charge: true,
        //  email: email,
        tokenId: accessToken,
        sourceId: nonce,
        verifyToken: buyerVerificationToken,
        patientId,
        providerId,
        providerName,
        //  amount,
        //  description: `$25 per visit charge on ${moment().format('LLL')} for ${name}`,
        merchantId,
        //  name,
      });

      // create a subscription
      const config = {
        headers: {
          Authorization: jwtToken,
          'Content-Type': 'application/json',
        },
      };
      const result = await axios.post(url, data, config);
      console.log(result, ' this is submit of token to back-end server.');
      const {
        data: {
          input: {
            response: {
              status,
            },
          },
        },
      } = result;
      if (status !== 200) {
        const { creditCardFailureMessage } = this.props;
        if (creditCardFailureMessage) return creditCardFailureMessage('error');
      }
      const { confirmPaid, creditCardSuccessMessage } = this.props;
      if (confirmPaid) confirmPaid();
      if (creditCardSuccessMessage) creditCardSuccessMessage();
    } catch (e) {
      console.error(e, ' something went wrong in submit action of PatientCheckoutFormSquare');
      const { creditCardFailureMessage } = this.props;
      if (creditCardFailureMessage) creditCardFailureMessage(e);
    }
  }

  createVerificationDetails = () => {
    const {
      lastName,
      firstName,
      email,
      city,
      address1,
      address2,
      postalCode,
      phone,
    } = this.props;
    return {
      amount: '25.00',
      currencyCode: 'USD',
      intent: 'CHARGE',
      billingContact: {
        familyName: lastName,
        givenName: firstName,
        email,
        country: 'US',
        city,
        addressLines: [address1, address2],
        postalCode,
        phone,
      },
    };
  }

  render() {
    return (
      <div className="dt w-100-ns checkout mw3 mw5-ns center blue">
        <div className="dtc v-mid pa2">
          <p>
            Would you like to complete the purchase?
          </p>
          <SquarePaymentForm
            className="h3-ns h2 ma3 ma2-ns"
            applicationId={APPLICATION_ID}
            locationId={LOCATION_ID}
            cardNonceResponseReceived={this.cardNonceResponseReceived}
            createVerificationDetails={this.createVerificationDetails}
            {...this.props}
          >
            <fieldset className="sq-fieldset">
              <CreditCardNumberInput />
              <div className="sq-form-third">
                <CreditCardExpirationDateInput />
              </div>

              <div className="sq-form-third">
                <CreditCardPostalCodeInput />
              </div>

              <div className="sq-form-third">
                <CreditCardCVVInput />
              </div>
            </fieldset>
            <CreditCardSubmitButton>
                Pay
            </CreditCardSubmitButton>
          </SquarePaymentForm>
        </div>
      </div>
    );
  }
}

//  const PatientCheckoutFormInjectSquare = injectStripe(PatientCheckoutForm);

const PatientCheckoutFormWithRouter = withRouter(PatientCheckoutForm);

export default PatientCheckoutFormWithRouter;
```

**Comment by rush86999** [comment]
ok so the direct url API works and this does not so I m switching to direct api calls.

**Comment by StephenJosey** [comment]
Thanks for the update @rush86999 . I know we were discussing this on Slack but just wanted to check in: is this working now?

**Comment by rush86999** [comment]
yes thanks. I m leaving this open as I think there is a bug in the nodejs sdk unless you guys want to close the issue.
